/**
 * Regression coverage for project-scoped batch compilation.
 *
 * The CLI imports batch files into the selected project's `sources/`
 * directory and then delegates to the regular compiler. This test proves
 * the delegated compile step writes wiki pages into that same project,
 * instead of incorrectly reporting success with no generated pages.
 */

import { describe, it, expect } from "vitest";
import { mkdir, mkdtemp, readdir, readFile, rm, writeFile } from "fs/promises";
import os from "os";
import path from "path";
import {
  mockClaudeEnv,
  startMockClaude,
  stopMockClaude,
} from "./fixtures/aimock-helper.js";
import { expectCLIExit, runCLI } from "./fixtures/run-cli.js";

async function makeBatchWorkspace(): Promise<{ root: string; input: string }> {
  const root = await mkdtemp(path.join(os.tmpdir(), "llmwiki-batch-project-"));
  const input = path.join(root, "batch-input");
  await mkdir(input, { recursive: true });
  await writeFile(
    path.join(input, "alpha.md"),
    "# Alpha\n\nAlpha explains the batch concept.",
    "utf-8",
  );
  await writeFile(
    path.join(input, "beta.md"),
    "# Beta\n\nBeta expands the same batch concept.",
    "utf-8",
  );
  return { root, input };
}

/** Configure the mock model to extract and write one batch concept. */
function mockBatchConcept(handle: Awaited<ReturnType<typeof startMockClaude>>): void {
  handle.mock.onToolCall("extract_concepts", {
    toolCalls: [
      {
        name: "extract_concepts",
        arguments: {
          concepts: [
            {
              concept: "Batch Concept",
              summary: "A concept extracted from batch input.",
              is_new: true,
              tags: ["batch"],
              confidence: 0.95,
            },
          ],
        },
      },
    ],
  });
  handle.mock.onMessage(/.*/, {
    content: "Batch concept body generated by the mock model.",
  });
}

/** Path to the project wiki directory for the batch regression project. */
function batchProjectWiki(root: string): string {
  return path.join(root, "projects", "batchdemo", "wiki");
}

describe("batch-compile project scope", () => {
  it("compiles imported files into the requested project's wiki", async () => {
    const handle = await startMockClaude();
    const workspace = await makeBatchWorkspace();

    try {
      mockBatchConcept(handle);

      expectCLIExit(
        await runCLI(["project", "add", "batchdemo", "Batch Demo"], workspace.root),
        0,
      );
      const result = await runCLI(
        ["batch-compile", workspace.input, "--batch", "2", "--project", "batchdemo"],
        workspace.root,
        mockClaudeEnv(handle),
      );

      expectCLIExit(result, 0);

      const projectWiki = batchProjectWiki(workspace.root);
      const conceptFiles = await readdir(path.join(projectWiki, "concepts"));
      expect(conceptFiles).toContain("batch-concept.md");

      const page = await readFile(
        path.join(projectWiki, "concepts", "batch-concept.md"),
        "utf-8",
      );
      expect(page).toContain("Batch Concept");
      expect(page).toContain("Batch concept body generated by the mock model.");
    } finally {
      await stopMockClaude(handle);
      await rm(workspace.root, { recursive: true, force: true });
    }
  }, 30_000);
});
